# Generated by Django 2.2.1 on 2020-01-09 18:12

from django.db import migrations, models
import django_google_maps.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientScreenName', models.CharField(default='', max_length=80)),
                ('mapCenter', django_google_maps.fields.GeoLocationField(default='0.0,0.0', max_length=100)),
                ('mapZoom', models.IntegerField(default=15)),
            ],
        ),
    ]
