# Generated by Django 2.2.1 on 2020-01-09 18:16

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fl_dashboard', '0002_preferences_mapcenter_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='mapCenter',
            field=django_google_maps.fields.GeoLocationField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='mapCenter_address',
            field=django_google_maps.fields.AddressField(max_length=200, null=True),
        ),
    ]
