# Generated by Django 2.2.1 on 2020-01-09 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fl_dashboard', '0003_auto_20200109_2016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preferences',
            old_name='mapCenter_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='preferences',
            old_name='mapCenter',
            new_name='geolocation',
        ),
    ]
