# Generated by Django 2.2.1 on 2020-01-31 23:25

from django.db import migrations, models
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fl_dashboard', '0004_auto_20200109_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='address',
            field=django_google_maps.fields.AddressField(max_length=200, null=True, verbose_name='Map Center Address'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(max_length=100, null=True, verbose_name='Map Center Coords'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='mapZoom',
            field=models.IntegerField(default=15, verbose_name='Map Zoom Level'),
        ),
    ]
