# Generated by Django 2.2.1 on 2020-07-19 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fl_meters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('volume', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fl_meters.Location')),
            ],
        ),
        migrations.CreateModel(
            name='TankLevelSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('name', models.CharField(blank=True, default='', help_text='If not provided, the Key will be used instead.', max_length=50)),
                ('installation_date', models.DateTimeField(blank=True, null=True)),
                ('reading_factor', models.DecimalField(blank=True, decimal_places=2, default=1, help_text='The division factor for each pulse going through this sensor.', max_digits=9)),
                ('reading_offset', models.DecimalField(blank=True, decimal_places=5, default=0, help_text='The offset amount for each pulse going through this sensor. Can also be a negative value.', max_digits=12)),
                ('active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fl_meters.DeviceModel')),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fl_meters.Tank')),
            ],
            options={
                'verbose_name': 'Tank Level Sensor',
                'verbose_name_plural': 'Tank Level Sensors',
            },
        ),
        migrations.CreateModel(
            name='TankLevelSensorPulse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('reading', models.DecimalField(decimal_places=3, max_digits=16)),
                ('normalized_reading', models.DecimalField(blank=True, decimal_places=3, max_digits=16, null=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fl_meters.TankLevelSensor')),
            ],
        ),
        migrations.CreateModel(
            name='TankLevel',
            fields=[
                ('datetime', models.DateTimeField(primary_key=True, serialize=False)),
                ('level', models.DecimalField(decimal_places=3, max_digits=13)),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fl_meters.Tank')),
            ],
        ),
    ]
