# Generated by Django 2.2.1 on 2020-07-25 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fl_meters', '0002_tank_tanklevelrecord_tanklevelsensor_tanklevelsensorpulse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytsminflow',
            name='consumption',
            field=models.DecimalField(decimal_places=3, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='dailytsmlossrecord',
            name='loss',
            field=models.DecimalField(decimal_places=3, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='dailyzoneconsumption',
            name='consumption',
            field=models.DecimalField(decimal_places=3, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='dailyzoneconsumption',
            name='p_afternoon',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='dailyzoneconsumption',
            name='p_dawn',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='dailyzoneconsumption',
            name='p_evening',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='dailyzoneconsumption',
            name='p_nighttime',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='dailyzoneconsumption',
            name='p_noon',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='dailyzoneloss',
            name='loss',
            field=models.DecimalField(decimal_places=3, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='monthlytsminflow',
            name='billed_consumption',
            field=models.DecimalField(decimal_places=3, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='monthlytsminflow',
            name='consumption',
            field=models.DecimalField(decimal_places=3, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='monthlytsmlossrecord',
            name='loss',
            field=models.DecimalField(decimal_places=3, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyzoneconsumption',
            name='billed_consumption',
            field=models.DecimalField(decimal_places=3, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyzoneconsumption',
            name='consumption',
            field=models.DecimalField(decimal_places=3, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyzoneloss',
            name='loss',
            field=models.DecimalField(decimal_places=3, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='quarterhourlytsminflow',
            name='consumption',
            field=models.DecimalField(decimal_places=3, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='quarterhourlyzoneconsumption',
            name='consumption',
            field=models.DecimalField(decimal_places=3, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='yearlytsminflow',
            name='consumption',
            field=models.DecimalField(decimal_places=3, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='yearlytsmlossrecord',
            name='loss',
            field=models.DecimalField(decimal_places=3, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='yearlyzoneconsumption',
            name='consumption',
            field=models.DecimalField(decimal_places=3, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='yearlyzoneconsumption',
            name='p_quarter1',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='yearlyzoneconsumption',
            name='p_quarter2',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='yearlyzoneconsumption',
            name='p_quarter3',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='yearlyzoneconsumption',
            name='p_quarter4',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='yearlyzoneloss',
            name='loss',
            field=models.DecimalField(decimal_places=3, max_digits=13, null=True),
        ),
    ]
