# Generated by Django 2.2.1 on 2020-09-09 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('fl_meters', '0003_auto_20200724_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='kind',
            field=models.CharField(choices=[('LK', 'Leak'), ('SK', 'Shock'), ('NM', 'Anomaly'), ('--', 'Undefined')], default='--', max_length=3),
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('since', models.DateTimeField()),
                ('until', models.DateTimeField(blank=True, null=True)),
                ('kind', models.PositiveSmallIntegerField(choices=[(0, 'Undefined'), (1, 'Interpolation'), (2, 'Anomaly'), (3, 'Estimation Confidence')], default=0)),
                ('value', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=250)),
                ('metric', models.PositiveSmallIntegerField(choices=[(0, 'Undefined'), (1, 'Meter Flowrate'), (2, 'Zone Consumption')], default=0)),
                ('target_id', models.PositiveIntegerField()),
                ('target_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
    ]
