# Generated by Django 2.2.1 on 2020-09-11 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fl_meters', '0004_auto_20200909_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='pulse',
            name='anomaly',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Annotation',
        ),
    ]
